apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui # pacman-gitops 
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui # pacman-gitops 
  template:
    metadata:
      labels:
        app: guestbook-ui # pacman-gitops 
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest #  quay.io/redhat-scholars/pacman-kikd:1.0.0 
        name: guestbook-ui # pacman-gitops 
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
