apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: masternginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        image: nginx:1.14.2
        port: "80"
      - cluster: prod
        url: https://aks197-dns-507c5200.hcp.centralus.azmk8s.io:443
        image: nginx:1.21.1
        port: "8080"
  template:
    metadata:
      name: '{{cluster}}-tensai'
    spec:
      project: default
      source:
        repoURL: https://github.com/tensai-for-release/argocd.git
        targetRevision: HEAD
        path: applicationsets
        helm:
          releaseName: '{{image}}-nginx'
          parameters:
          - name: image
            value: '{{image}}'
          - name: port
            value: '{{port}}'  
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated: {}
