apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tensainginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: tensai-dev
        url: https://kubernetes.default.svc
        image: nginx:1.14.2
        port: "80"
      - cluster: tensai-prod
        url: https://argotestaks-dns-885ac337.hcp.eastus.azmk8s.io:443
        image: nginx:1.21.1
        port: "8080"
      - cluster: tensai-stage
        url: https://tensai-dev-dns-ae4b433d.hcp.southindia.azmk8s.io:443
        image: nginx:1.21.1
        port: "8080"
  template:
    metadata:
      name: '{{cluster}}-environment'
    spec:
      project: default
      source:
        repoURL: https://github.com/tensai-for-release/argocd.git
        targetRevision: HEAD
        path: applicationsets/appsets
        helm:
          releaseName: '{{image}}-nginx'
          parameters:
          - name: image
            value: '{{image}}'
          - name: port
            value: '{{port}}'  
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated: {}
