apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
spec:
 generators:
 - list:
     elements:
     - cluster: engineering-dev
       url: https://kubernetes.default.svc
     - cluster: engineering-prod
       url: https://aks197-dns-507c5200.hcp.centralus.azmk8s.io:443
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/tensai-for-release/argocd.git
       targetRevision: HEAD
       path: appsets/list-generator/guestbook/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: guestbook-ns
     syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true
