apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-maven-app
  namespace: sample-maven-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sample-maven-app
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: sample-maven-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
