apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-maven-app
  namespace: sample-maven-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sample-maven-app
    server: https://argotestaks-dns-885ac337.hcp.eastus.azmk8s.io:443
  project: default
  source:
    path: helm-hooks
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
